def load_socket_commands():
    from . import (
        asset,
        asset_manager,
        client,
        connection,
        dashboard,
        dice,
        floor,
        groups,
        initiative,
        label,
        lg,
        location,
        logic,
        marker,
        note,
        player,
        room,
        shape,
        user,
    )
