def load_socket_commands():
    from . import asset  # noqa: F401.
    from . import asset_manager  # noqa: F401.
    from . import client  # noqa: F401.
    from . import connection  # noqa: F401.
    from . import dashboard  # noqa: F401.
    from . import dice  # noqa: F401.
    from . import floor  # noqa: F401.
    from . import groups  # noqa: F401.
    from . import initiative  # noqa: F401.
    from . import label  # noqa: F401.
    from . import lg  # noqa: F401.
    from . import location  # noqa: F401.
    from . import logic  # noqa: F401.
    from . import marker  # noqa: F401.
    from . import note  # noqa: F401.
    from . import player  # noqa: F401.
    from . import room  # noqa: F401.
    from . import shape  # noqa: F401.
    from . import user  # noqa: F401.
